#!/usr/bin/python
# encoding: utf-8

food_list =	[["","","","",""],
	["acolyte", "400", "Human", "",""],
	["ape", "500","", "","" ],
	["apprentice", "400", "Human", "",""],
	["attendant", "400", "Human","",""],
	["archeologist", "400", "Human","",""],
	["barbarian", "400", "Human","",""],
	["baluchitherium", "800","","",""],
	["bat", "20","", "Stun (30)",""],
	["bugbear", "250","","","" ],
	["captain", "400", "Human","",""],
	["caveman", "400", "Human","",""],
	["cavewoman", "400", "Human","",""],
	["centipede", "50","", "", "Poison: 13%"],
	["chameleon", "100","", "Polymorph", "" ],
	["chickatrice", "10", "Petrify", "","Poison: 27%"],
	["chieftain", "400", "Human","",""],
	["cobra", "100", "Poisonous","","Poison: 40%"],
	["cockatrice", "30", "Petrify", "","Poison: 33%"],
	["coyote", "250","","","" ],
	["crocodile", "400","","","" ],
	["Croesus", "400", "Human","",""],
	["Cyclops", "700","", "Strength",""],
	["Death", "1", "DIE","",""],
	["dingo", "200","","","" ],
	["disenchanter", "200","","","" ],
	["dog", "200", "Aggravate" , "",""],
	["doppelganger", "400", "Human", "Polymorph" ,""],
	["elf", "350", "Elf", "","Sleep: 67%"],
	["elf-lord", "350", "Elf", "","Sleep: 53%"],
	["Elvenking", "350", "Elf", "","Sleep: 60%"],
	["ettin", "500","", "",""],
	["Famine", "1", "DIE", "",""],
	["dwarf", "300", "Dwarf", "",""],
	["fox", "250","", "",""],
	["gecko", "20","", "",""],
	["giant", "750","" ,"Strength",""],
	["gnome", "100", "Gnome", "", ""],
	["goblin", "100","", "", "" ],
	["gargoyle", "200","", "", "" ],
	["Green-elf", "350", "Elf", "","Sleep: 33%"],
	["gremlin", "20", "Poisonous", "","Poison: 33%"],
	["Grey-elf", "350", "Elf", "","Sleep: 40%"],
	["guard", "400", "Human" ,"",""],
	["guide", "400", "Human" ,"",""],
	["healer", "400", "Human" ,"",""],
	["Hippocrates", "400", "Human" ,"",""],
	["hobbit", "200","","","" ],
	["hobgoblin", "200","" ,"",""],
	["homunculus", "100", "Poisonous", "","Sleep: 7%, Poison: 7%"],
	["horse", "300","","","" ],
	["housecat", "200", "Aggravate" ,"",""],
	["human", "400", "Human" ,"",""],
	["hunter", "400", "Human" ,"",""],
	["iguana", "30","","","" ],
	["imp", "10","","","" ],
	["Ixoth", "1600","", "", "Fire: 100%"],
	["jabberwock", "600","" ,"",""],
	["kitten", "150", "Aggravate" ,"",""],
	["knight", "400", "Human" ,"",""],
	["jackal", "250","" ,"",""],
	["jaguar", "300","" ,"",""],
	["jellyfish", "20", "Poisonous", "","Poison: 20%"],
	["kobold", "100", "Poisonous" ,"",""],
	["kraken", "1000","" ,"",""],
	["leocrotta", "500","" ,"",""],
	["leprechaun", "30","", "", "Teleportitis: 50%"],
	["lichen", "200 V!", "","",""],
	["lizard", "40", "Cure stoning, Reduce stunning, confusion", "",""],
	["lieutenant", "400", "Human" ,"",""],
	["lynx", "300","" ,"",""],
	["Medusa", "400", "Petrify, Poisonous", "","Poison: 100%"],
	["mastodon", "800","" ,"",""],
	["minotaur", "700","" ,"",""],
	["mumak", "500","" ,"",""],
	["neanderthal", "400", "Human" ,"",""],
	["newt", "20","", "","Energy: 67%"],
	["ninja", "400", "Human" ,"",""],
	["Norn", "400", "Human" ,"",""],
	["nurse", "400", "Human","Heal","Poison: 73%"],
	["monk", "400", "Human" ,"",""],
	["monkey", "50","","","" ],
	["ogre", "500","","","" ],
	["Oracle", "400", "Human" ,"",""],
	["orc-captain" "350", "" ,"",""],
	["pony", "250","" ,"",""],
	["priest", "400", "Human" ,"",""],
	["priestess", "400", "Human" ,"",""],
	["prisoner", "400", "Human" ,"",""],
	["Orion", "400", "Human" ,"",""],
	["owlbear", "700","" ,"",""],
	["page", "400", "Human" ,"",""],
	["panther", "300","" ,"",""],
	["Pelias", "400", "Human" ,"",""],
	["Pestilence", "1", "DIE" ,"",""],
	["piranha", "30","" ,"",""],
	["orc", "150","","","" ],
	["Olog-hai", "400", "","",""],
	["pyrolisk", "30","", "", "Fire: 20%, Poison: 20%"],
	["python", "100","" ,"",""],
	["quasit", "200","", "","Poison: 20%"],
	["ranger", "400", "Human" ,"",""],
	["raven", "20","","","" ],
	["rogue", "400", "Human" ,"",""],
	["roshi", "400", "Human" ,"",""],
	["salamander", "400", "Poisonous", "","Fire: 53%"],
	["samurai", "400", "Human" ,"",""],
	["rothe", "100","" ,"",""],
	["sasquatch", "750","" ,"",""],
	["scorpion", "100", "Poisonous" , "","Poison: 50%"],
	["Scorpius", "350", "Poisonous" , "","Poison: 100%"],
	["student", "400", "Human" ,"",""],
	["tengu", "200","", "", "Poison: 13%, Teleportitis: 20%, Teleport control: 17%"],
	["thug", "400", "Human" ,"",""],
	["tiger", "300","","","" ],
	["titan", "900","" ,"",""],
	["titanothere", "650","","","" ],
	["snake", "80", "Poisonous", "","Poison: 27%"],
	["soldier", "400", "Human" ,"",""],
	["stalker", "400","", "Stun (60)" ,"Invisibility"],
	["shark", "350","" ,"",""],
	["shrieker", "100 V!", "" , "" ,"Poison: 20%"],
	["shopkeeper", "400", "Human" ,"",""],
	["sergeant", "400", "Human" ,"",""],
	["tourist", "400", "Human" ,"",""],
	["trapper", "350","","","" ],
	["Uruk-hai", "300", "" ,"",""],
	["valkyrie", "400", "Human" ,"",""],
	["warg", "350","","","" ],
	["warhorse", "350","" ,"",""],
	["warrior", "400", "Human" ,"",""],
	["werejackal", "400", "Human, Poisonous" ,"","Lycanthropy: 100%"],
	["wererat", "400", "Human, Poisonous" ,"","Lycanthropy: 100%"],
	["werewolf", "400", "Human, Poisonous" ,"","Lycanthropy: 100%"],
	["watchman", "400", "Human" ,"",""],
	["troll", "350","","","" ],
	["Twoflower", "400", "Human" ,"",""],
	["wizard", "400", "Human","",""],
	["wraith", "0","","Gain level",""],
	["wumpus", "500","","","" ],
	["xan", "300", "Poisonous" ,"","Poison: 47%"],
	["xorn", "700","" ,"",""],
	["yeti", "700","", "" , "Cold: 33%"],
	["zruty", "600","" ,"",""],
	["Woodland-elf", "350", "Elf", "" ,"Sleep: 27%"],
	["woodchuck", "30","","","" ],
	["wolf", "250","" ,"",""],
	["acid blob", "10 V!", "Acidic", "", ""],
	["winged gargoyle", "300","", "", ""],
	["wood nymph", "300", "", "","Teleportitis: 30%"],
	["winter wolf", "300", "", "","Cold: 47%"],
	["yellow dragon", "1500","Acidic", "", ""],
	["yellow mold", "30 V!", "Poisonous","Hallucination","Poison: 7%"],
	["umber hulk", "500","", "", ""],
	["vampire bat", "20","Poisonous", "", ""],
	["violet fungus", "100 V!","Hallucination", "", "Poison: 20%"],
	["watch captain", "400","Human", "", ""],
	["water moccasin", "80","Poisonous", "","Poison: 27%"],
	["water nymph", "300","","","Teleportitis: 30%"],
	["water troll", "350","", "", ""],
	["white dragon", "1500","" , "","Cold: 100%"],
	["white unicorn", "300","", "","Poison: 27%"],
	["sewer rat", "12","", "", "" ],
	["Shaman Karnov", "400","Human", "",""],
	["silver dragon", "1500","", "", ""],
	["small mimic", "200","", "Mimic (20)", ""],
	["soldier ant", "5","Poisonous", "","Poison: 20%"],
	["spotted jelly", "20 V!","Acidic", "", ""],
	["stone giant", "750","", "Strength", ""],
	["storm giant", "750","","Strength","Shock: 50%"],
	["purple worm", "700","", "", "" ],
	["quantum mechanic", "20","Poisonous", "","Speed Toggle"],
	["queen bee", "5","Poisonous", "","Poison: 60%"],
	["quivering blob", "100 V!", "", "","Poison: 33%"],
	["rabid rat", "5","Poisonous", "", ""],
	["red dragon", "1500","", "","Fire: 100%"],
	["red mold", "30 V!", "", "","Fire: 3%, Poison: 3%"],
	["red naga", "400","", "","Fire: 20%, Poison: 20%"],
	["rock mole", "30","", "", "" ],
	["rock piercer", "200","", "", ""],
	["rock troll", "300","", "", ""],
	["rust monster", "250","", "", ""],
	["ochre jelly", "20 V!", "Acidic", "", ""],
	["ogre king", "750","", "", ""],
	["ogre lord", "700","", "", ""],
	["orange dragon", "1500","","","Sleep: 100%"],
	["orc shaman", "300","", "", "" ],
	["pit viper", "60","Poisonous", "","Poison: 40%"],
	["plains centaur", "500","", "", "" ],
	["lurker above", "350","", "", "" ],
	["Master Assassin", "400","Human", "", ""],
	["mind flayer", "400","", "","Intelligence: 50%, Telepathy: (if no Intelligence gain)"],
	["mountain centaur", "500","", "", ""],
	["Master Kaen", "400","Human", "","Poison: 100%"],
	["mountain nymph", "300","" , "","Teleportitis: 30%"],
	["Mordor orc", "200","", "", ""],
	["kobold lord", "200","Poisonous", "", ""],
	["kobold shaman", "150","Poisonous", "", ""],
	["Kop Kaptain", "200","Human", "", ""],
	["Kop Lieutenant", "200","Human", "", ""],
	["Kop Sergeant", "200","Human", "", ""],
	["large cat", "250","Aggravate", "", ""],
	["large dog", "250","Aggravate", "", ""],
	["large kobold", "150","Poisonous", "", ""],
	["large mimic", "400","","Mimic (40)", ""],
	["little dog", "150","Aggravate", "", ""],
	["long worm", "500","", "", ""],
	["Lord Carnarvon", "400","Human", "", ""],
	["Lord Sato", "400","Human", "", ""],
	["Lord Surtur", "850","","Strength", "Fire: 50%"],
	["ice troll", "300","", "","Cold: 60%"],
	["iron piercer", "300","", "", ""],
	["Keystone Kop", "200","Human", "", ""],
	["killer bee", "5","Poisonous", "","Poison: 30%"],
	["King Arthur", "400","Human", "", ""],
	["Grand Master", "400","Human", "", ""],
	["gray dragon", "1500","", "", ""],
	["gray ooze", "250 V","Acidic", "","Fire: 7%, Cold: 7%, Poison: 7%"],
	["gray unicorn", "300","","","Poison: 27%"],
	["green dragon", "1500","Poisonous", "","Poison: 100%"],
	["green mold", "30 V!","Acidic", "", ""],
	["green slime", "150 V","Slime, Poisonous, Acidic", "", ""],
	["guardian naga", "400","Poisonous", "","Poison: 80%"],
	["hell hound", "300","", "","Fire: 80%"],
	["high priest", "400","Human", "", ""],
	["hill giant", "700","","Strength", ""],
	["hill orc", "200","", "", "" ],
	["forest centaur", "600","", "", ""],
	["frost giant", "750","","Strength","Cold: 33%"],
	["garter snake", "60","", "", "" ],
	["gelatinous cube", "150 V!", "Acidic", "","Fire: 10%, Cold: 10%, Sleep: 10%, Shock: 10%"],
	["giant ant", "10","", "", ""],
	["giant bat", "30","", "Stun (60)", ""],
	["giant beetle", "10","Poisonous", "","Poison: 33%"],
	["giant eel", "250","", "", ""],
	["giant mimic", "500","" , "Mimic (50)", ""],
	["giant rat", "30","", "", ""],
	["giant spider", "100","Poisonous", "","Poison: 33%"],
	["glass piercer", "300","", "", ""],
	["gnome king", "150","Gnome", "", ""],
	["gnome lord", "120","Gnome", "", ""],
	["gnomish wizard", "120","Gnome", "", ""],
	["golden naga", "400","", "","Poison: 67%"],
	["aligned priest", "400","Human", "", ""],
	["Arch Priest", "400","Human", "", ""],
	["baby crocodile", "200","", "", ""],
	["black dragon", "1500","", "","Disintegration: 100%"],
	["black naga", "400","Acidic", "","Poison: 53%"],
	["black pudding", "250","Acidic", "","Cold: 22%, Shock: 22%, Poison: 22%"],
	["black unicorn", "300","", "","Poison: 27%"],
	["blue dragon", "1500","", "","Shock: 100%"],
	["blue jelly", "20 V!","", "","Cold: 13%, Poison: 13%"],
	["brown mold", "30 V!","", "","Cold: 3%, Poison: 3%"],
	["brown pudding", "250 V", "Acidic", "","Cold: 11%, Shock: 11%, Poison: 11%"],
	["carnivorous ape", "550","", "", ""],
	["cave spider", "50","", "","Poison: 7%"],
	["Chromatic Dragon", "1700","Poisonous", "","Fire: 17%, Cold: 17%, Sleep: 17%, Shock: 17%, Poison: 17%, Disintegration: 17%"],
	["dwarf king", "300","Dwarf", "", ""],
	["dwarf lord", "300","Dwarf", "", ""],
	["electric eel", "250","", "","Shock: 47%"],
	["fire ant", "10","", "","Fire: 20%"],
	["fire giant", "750","","Strength", "Fire: 30%"],
	["flesh golem", "600","","","Fire: 12%, Cold: 12%, Sleep: 12%, Shock: 12%, Poison: 12%"],
	["floating eye", "10", "", "","Telepathy: 100%"],
	["baby black dragon", "500","", "", ""],
	["baby blue dragon", "500","", "", ""],
	["baby gray dragon", "500","", "", ""],
	["baby green dragon", "500", "Poisonous", "",""],
	["baby long worm", "250","", "", ""],
	["baby orange dragon", "500", "", "", ""],
	["baby purple worm", "250", "", "", ""],
	["baby red dragon", "500", "", "", ""],
	["baby silver dragon", "500", "", "", ""],
	["baby white dragon", "500", "", "", ""],
	["baby yellow dragon", "500", "Acidic", "", ""],
	["black naga hatchling", "100", "Acidic", "","Poison: 20%"],
	["golden naga hatchling", "100", "", "","Poison: 20%"],
	["guardian naga hatchling", "100", "","","Poison: 20%"],
	["hell hound pup", "200", "", "","Fire: 47%"],
	["master mind flayer", "400","", "", "Intelligence: 50%, Telepathy: (if no Intelligence gain)"],
	["Master of Thieves", "400", "Human", "", ""],
	["Neferet the Green", "400", "Human", "", ""],
	["red naga hatchling", "100","", "", "Fire: 10%, Poison: 10%"],
	["winter wolf cub", "200", "", "","Cold: 33%"],
	["Wizard of Yendor", "400", "Human", "","Fire: 25%, Poison: 25%, Teleportitis: 25%, Teleport control: 25%"]]